### PR TITLE
core/Mouse: add isPressedIn method

### LINKED ISSUE #104: implement mouse.isPressedIn(shape)
The PsychoPy lib supports 
`mouse.isPressedIn(stim)` 
returning a bool. This was always just a shorthand for
`sum(mouse.buttons())>0 and stim.contains(mouse)`
and although I personally considered it unecessary it is reasonably widely used so seems sensible to implement. 

You can see the Python implementation at 
https://github.com/psychopy/psychopy/blob/7ea4a9e81c585eb4e57b919837fe8268b4144345/psychopy/event.py#L856

### PR DESCRIPTION
**Pull request by thewhodidthis**
@apitiot @peircej Implement `Mouse.isPressedIn()` with a slightly different signature to PsychoPy when it comes to targeting a specific button. Closes #104?

Demo:
http://succinct-harbor.surge.sh

### CODE REVIEW

**Comment by peircej** [comment]
>with a slightly different signature to PsychoPy

Would it be possible to use the same signature? that way auto-translating the code from Python syntax into JS is all that's needed. e.g. if someone has written a Python code snippet:
```
isPressed = mouse.isPressedIn(myStim, buttons=1)
```
then we'd like it to work without them needing to change `buttons` into `wanted`. Doesn't matter if the way it works under the hood changes but we want the in/out to look the same wherever possible

**Comment by thewhodidthis** [comment]
No problem, maybe I'm missing something, the second argument is an array (list) then? The snippet you have posted includes an assignment into buttons inline? Is that a python idiom?

**Comment by peircej** [comment]
Ah. In Python you can either specify arguments either in their order or according to the _name_ so these are equivalent:
```python
mouse.isPressedIn(shape=myStim, buttons=1)
mouse.isPressedIn(myStim, buttons=1)
mouse.isPressedIn(myStim, 1)
```
It's useful if you want to skip some of the arguments and use the final one, or if you don't remember the order.

Oh, but if JS doesn't allow arguments to be named then the first two versions above can't be used anyway in JS? In that case there's less need to have the same names other than it looking the same!

**Comment by peircej** [comment]
I just read your comment: "Since there can only be one button pressed at a time..."

In Python you can certainly detect two buttons down simultaneously. Is that not possible in JS?

But the aim is to allow the user to specify more than one button to check. What if the user is happy for the right or left buttons to be pressed but not middle? Is that handled in your code? It's rare but if it's easy then let's handle it straight away

**Comment by thewhodidthis** [comment]
> Oh, but if JS doesn't allow arguments to be named then the first two versions above can't be used anyway in JS? In that case there's less need to have the same names other than it looking the same!

Named arguments per se are unavailable. Passing in an object with keys named after each variable might come close. For example,

```js
const areTheLeftAndRightButtonsPressedInMyStim = mouse.isPressedIn({ stim: myStim, buttons: [1, 0, 1] })
```

**Comment by peircej** [comment]
OK, I checked to see what Alain's auto-translate in PsychoPy does with those. It gives:
```python
mouse.isPressedIn(shape=myStim, buttons=1)
mouse.isPressedIn(myStim, buttons=1)
mouse.isPressedIn(myStim, 1)
```
->
```javascript
mouse.isPressedIn({"shape": myStim, "buttons": 1});
mouse.isPressedIn(myStim, {"buttons": 1});
mouse.isPressedIn(myStim, 1);
```

**Comment by peircej** [comment]
So if you could make the function handle inputs like that it would be great! :-)

**Comment by thewhodidthis** [comment]
> OK, I checked to see what Alain's auto-translate in PsychoPy does with those. It gives:
> 
> ```python
> mouse.isPressedIn(shape=myStim, buttons=1)
> mouse.isPressedIn(myStim, buttons=1)
> mouse.isPressedIn(myStim, 1)
> ```
> 
> ->
> 
> ```js
> mouse.isPressedIn({"shape": myStim, "buttons": 1});
> mouse.isPressedIn(myStim, {"buttons": 1});
> mouse.isPressedIn(myStim, 1);
> ```

Alright, that's clear now, thanks

**Comment by thewhodidthis** [comment]
> I just read your comment: "Since there can only be one button pressed at a time..."
> 
> In Python you can certainly detect two buttons down simultaneously. Is that not possible in JS?

Please correct me if I'm wrong, I'm working within the context of how PsychoJS pointer event handlers are set up. Multiple button combinations seem unsupported at the moment:

https://github.com/psychopy/psychojs/blob/master/js/core/EventManager.js#L241

**Comment by thewhodidthis** [comment]
> ```js
> mouse.isPressedIn(myStim, 1);
> ```

This is how it works at the moment, the rest is very much doable no problem!

**Comment by thewhodidthis** [comment]
> In Python you can certainly detect two buttons down simultaneously. Is that not possible in JS?

Detecting multiple parallel button presses seems only possible when listening for `mousedown` instead of pointer events.

**Comment by thewhodidthis** [comment]
@peircej I've updated the PR and example to reflect the spec above. I need come back to this tomorrow to improve the JSDoc for each type of input. @apitiot A test for the arguments parsing bit can be found [here &rsaquo;](https://gist.github.com/thewhodidthis/3119860f38e43c6799cf255d7b025c76)

**Comment by tpronk** [comment]
Hey guys, I built a little e2e test for isPressedIn. I noticed a small difference between the demo of @thewhodidthis ([http://succinct-harbor.surge.sh](http://succinct-harbor.surge.sh)) and my test in PsychoPy ([https://pavlovia.org/tpronk/e2e_buttons](https://pavlovia.org/tpronk/e2e_buttons).

In the PsychoPy version, if I click inside of a shape, then leave the shape while keeping the mouse button down (i.e. drag), then isPressedIn gets updated. In the JS version, this doesn't happen.

**Pull request merged**
