### PR TITLE
visual/Slider/Form/TextBox: towards implementing five color model

### LINKED ISSUE #315: Form component needs color options to match PsychoPy
Context: https://github.com/psychopy/psychopy/pull/3749

### PR DESCRIPTION
**Pull request by thewhodidthis**
@apitiot @TEParsons Closes #315

Demo:
[pavlovia.org/thewhodidthis/colorful-bfi &rarr;](https://pavlovia.org/thewhodidthis/colorful-bfi)

### CODE REVIEW

**Comment by apitiot** [comment]
Does this satisfy a very pressing need? If not, I started work on a Skin approach for Slider, as you saw, and I believe we should have a discussion about whether we should move away from it all together, or adopt what I perceive as the rather unmaintainable strategy of adding an ever increasing number of colour parameters in the constructor.
What are your views?

**Comment by thewhodidthis** [comment]
No problem, happy to discuss further. Only trying to bring parity with PsychoPy, Jon's already pulled those changes in with https://github.com/psychopy/psychopy/pull/3749 having first confirmed with me that we should be able to make them available on the JS side in time for the next release.

**Comment by apitiot** [comment]
Okidoki. Let's go with it, then, for now.
And let us have a more reasonable approach in place for the next release.

**Comment by thewhodidthis** [comment]
Sounds good, thanks

**Pull request merged**
