### PR TITLE
util/PsychObject: Expand on the has changed comparison when setting attributes

### PR DESCRIPTION
**Pull request by thewhodidthis**
@apitiot @peircej #144 This at least seems to guarantee a `stim.pos = [x, y]` update gets picked up. I believe that would work without any patching even. I'm currently looking into what happens when the color attribute is adjusted in a similar fashion.

### CODE REVIEW

**Comment by apitiot** [comment]
Good evening,

This is a little bit tricky. To begin with, as you have noticed, I made changes to PsychObject while you yourself were working on it. My apologies for the mishap!

As a consequence, we should return false when previousAttributeValue is undefined:

```
if (typeof previousAttributeValue === 'undefined')
{
	// Not that any of the following lines should throw, but evaluating
	// `this._vertices.map` on `ShapeStim._getVertices_px()` seems to
	return false;
}
```
Could you clarify your comment about exceptions being raised? Or perhaps you have an example?

Regarding the code below:

```
// Need check for equality differently for each type of attribute somehow,
// Lodash has an example of what an all encompassing solution looks like below,
// https://github.com/lodash/lodash/blob/master/.internal/baseIsEqualDeep.js
const prev = toString(previousAttributeValue);
const next = toString(attributeValue);

// Objects that belong to us such as colors feature a `toString()`
// method, exclude others that don't, important in turn when figuring
// out a `hasChanged` in a `ShapeStim.setPost()` for example
return prev !== 'Object (circular)' && next !== 'Object (circular)' && prev !== next;
```

I like the clever use of toString. However your comment about excluding objects without a toString method is a bit obscure, especially given that ShapeStim. setPost does not exist. Perhaps you meant setPos but that does not quite make sense either since passing an array to toString will return a nice string representation of it. Could you clarify a bit?

**Comment by thewhodidthis** [comment]
Hey Alain, you're so right! Sorry, that comment needed more work. The opposite of problematic, I meant `ShapeStim.setPos()` might be an example of how the check in question comes into play :blush:

I went back to fix the typo and better explain my thinking (hopefully). Like you describe, I've patched the script to return `false` when `previousAttributeValue` is undefined and remain on standby for further amends if need be.

**Comment by apitiot** [comment]
I am a bit surprised by the following line:
`return prev !== 'Object (circular)' && next !== 'Object (circular)' && prev !== next;`

If either of the values (old and new) are "opaque" to toString, might it not be preferable to assume that they are different? Or am I missing something?

**Comment by thewhodidthis** [comment]
@apitiot Was I being too cautious? I created[ a test script](https://repl.it/repls/AnchoredImpeccableBrain) to clarify my thinking. I don't see how we can simplify further, but I'm probably missing something. What would be the ideal formulation in your view?

**Comment by apitiot** [comment]
My point is mostly that if the string representation of the old or new attribute value is "Object (circular)" than we cannot really say whether the new value is different from the old one. And so it would seem safer to return true, which, typically, means that the PIXI representation will be updated.
What do you think?

**Comment by thewhodidthis** [comment]
Ah yes, it did cross my mind that that was what you meant :blush: Alright, let me try something a bit simpler

**Comment by thewhodidthis** [comment]
@apitiot OK `PsychObject._setAttribute()` will now return true if the previous and next values are different from each other or if either one is 'Object (circular)'

**Pull request merged**
