### PR TITLE
ENH: some changes in support of automated testing (and one for easier committing)

### PR DESCRIPTION
**Pull request by tpronk**
This PR contains the following changes:
* **d92d875 Prefix cross-var with npx, so it runs in GitHub.** The cross-var package adapts npm environment variables to the right format for bash (`$npm_package_version`) and Windows (`%npm_package_version%`). I have added the cross-var package and accidentally committed it directly to PsychoJS. This change prefixed calls to cross-var with npx, so that it also works in GitHub Actions.
* **9c28f51 Write captured errors to body.data-report attribute.** When a wdio test fails, it looks in document.data-error whether any JS error messages are stored there. This change makes sure that captures errors get stored into document.data-error.
* **54e21ff package-lock needed to cache dependencies in GitHub Workflows.** Installing psychojs into a GitHub Action can be done out of cache, by looking in package-lock.json, which speeds up the Action significantly. This change adds package-lock.json to the repo.
* **54e21ff Ignore node_modules directory** Add node_mouldes to .gitignore, so it doesn't accidentally get committed.

### CODE REVIEW

**Comment by thewhodidthis** [comment]
@tpronk Sorry why are you running cross-var via npx in the build:css script? Is that also a Windows thing?

**Comment by tpronk** [comment]
It's for the GitHub workflow; on their VMs, CLI commands like cross-var and wdio only work when prefixed by npx

**Comment by tpronk** [comment]
Do you mean as in "why does only the build:css" need prefixing? If so, that's because only build:css uses an npm variable (`$npm_package_version`)

**Comment by tpronk** [comment]
Yes, but indirectly: the actions invoke psychojs_testing/test.cjs, this one builds the library, deploys the test-experiments, then runs the tests. See [this line](https://github.com/psychopy/psychojs_testing/blob/7ea2bf13b0603c448bd3f99e6da7dd83ac5c25a0/test.cjs#L22)

**Comment by tpronk** [comment]
We need `cross-var` to have `$npm_package_version` play nice with Windows in `build:css`. We need `npx` to have `cross-var` play nice with GitHub Actions

**Comment by thewhodidthis** [comment]
Why do we not need npx to run build:js?

**Comment by tpronk** [comment]
Because its npm script doesn't use any npm variables (like `$npm_package_version`)

**Comment by tpronk** [comment]
Bit more :). On Windows, `$npm_package_version` isn't recognized, but `%npm_package_version%` is; cross-var takes care of that.

**Pull request merged**
