### PR TITLE
BF: Prevent user from unintentionally reloading the page when attempting to submit GUI.dlgFromDict by pressing Enter

### PR DESCRIPTION
**Pull request by sijiazhao**
BF: Remove `<form>...</form>` elements

Usual user expectation is the ability to submit forms by pressing Enter.

Because the intention is for the user to proceed by pressing the 'Ok' button on the jQuery dialog, submitting the form should be prevented. Easiest way is to omit `<form>...</form>`.

Leaving the elements means that a user can press Enter to submit the form. Since there is no `action="..."` attribute, the form will default to submitting the form to the current page, effectively causing a page reload. This only serves to annoy the user: the user may have to re-complete some fields, the user has to wait for previously downloaded resources to re-download etc.

### CODE REVIEW

**Comment by sijiazhao** [comment]
If you want to maintain users' functional expectation of pressing Enter, you could tie an `onsubmit` event to a 'Ok' button `click` event, along with `preventDefault()`.

**Comment by sijiazhao** [comment]
RE: commit 42ebec3 and revert 575c54b, please disregard, I accidentally pushed another fix into the wrong branch

**Comment by thewhodidthis** [comment]
Hi @sijiazhao, thanks for taking the time to contribute, apologies I was unable to repond sooner. Good point, do you see automatically giving the OK button focus implemented with #163 as helping in the same direction? Or would you be open to coding up the workaround you mention? As you know the OK button is disabled by default and while resources are being downloaded so removing the form element seems rather extreme in this context

**Comment by sijiazhao** [comment]
Hi, @thewhodidthis, removing the `form` element was merely the simplest fix for this bug. In any case, the OK button is not a child of the `form` so the button would not be triggered by pressing Enter anyway.

I will put something together for my workaround, which will probably involve something on the lines of:
`$("#the-dialog's-id??? form").on('submit', function() { ... })`.

Also (apologies if I'm wrong, I haven't tested this, I only had a quick scan through `GUI.js`), I'm not convinced by #163, because this looks like it would steal focus unexpectedly: if the downloads complete while the user is still typing inside one of the text inputs, focus would switch to the OK button, which can now be accidentally triggered by pressing `spacebar`.

For example, the question is "What is your favourite food?" and I answer "apple pie", but resources are fully downloaded part-way through `apple`. If I do not immediately notice the focus change and keep typing, when I get to `space` the OK button will trigger unexpectedly. In any case, stealing focus from an active input is annoying and unexpected.

Maybe I can submit a PR to fix this one too? something like:
`if (document.activeElement.tagName !== "INPUT") { // safe to steal focus }`

**Comment by thewhodidthis** [comment]
Hi @sijiazhao, interesting, thanks. Alright, removing the `<form>` element would be preferable to adding logic. To make sure I understand correctly, when I visit [a random project](https://run.pavlovia.org/thewhodidthis/blank), type my name in the participant field or edit session ID, and hit enter, nothing happens. How is that different to [no form demo](https://run.pavlovia.org/thewhodidthis/dialog-box-form-not) behaviour?

**Comment by sijiazhao** [comment]
Hi @thewhodidthis, what an interesting bug!

Here's what I've found from some quick testing. I haven't done any digging to find the cause of this behaviour:

With your example, which has _two fields_, then it's as you say: nothing happens.
If I test with a fresh project with _only one field_, then I can reproduce the bug.
If I use a browser debugger and _delete one of the fields from the DOM_ on your example, then I can also reproduce the bug.

(Tested in Windows 10 Firefox 86 and Chrome 88)

**Review by thewhodidthis — APPROVED** [review]

**Pull request merged**
