### PR TITLE
22ybvdr Textbox parity between psychoJS and psychoPy

### PR DESCRIPTION
**Pull request by lightest**

### CODE REVIEW

**Comment by lightest** [comment]
Subtasks done:
textbox fillColor: https://app.clickup.com/t/22ybzrp

**Comment by lightest** [comment]
Subtasks done:
anchoring and alignment: https://app.clickup.com/t/22ybxve

**Comment by lightest** [comment]
Subtasks done:
"greedy" focus: https://app.clickup.com/t/22ybz82

**Comment by peircej** [comment]
Task linked: [CU-22ybvdr Textbox: Parity between JS and Py](https://app.clickup.com/t/22ybvdr)

**Comment by lightest** [comment]
Subtasks done:
textbox text removed on each trial: https://app.clickup.com/t/22yh2gc
textbox size=none means fit to content: https://app.clickup.com/t/22yc092

**Review by apitiot — APPROVED** [review]

**Pull request merged**
