### PR TITLE
BF: Make seedrandom work again

### PR DESCRIPTION
**Pull request by tpronk**
This bug-fix consists of modifications to util.shuffle and TrialHandler:
1. `util.shuffle` supports an optional second argument, rng, which defaults to Math.random
2. TrialHandler now has a getter and setter for the seed attrbute. On setting this attribute it constructs a random number generator (rng) using seedrandom and the seed provided. This rng is passed to `util.shuffle` when preparing a sequence with method RANDOM or FULL_RANDOM

The tests of these modifications can be found in: https://github.com/psychopy/psychojs_testing/blob/main/tests/karma_randomization/karma_randomization.js

### CODE REVIEW

**Review by apitiot — COMMENTED** [review]
Almost perfect :-)

As per our little chat, you would need to refactor set seed into setSeed(seed, log)

**Comment by tpronk** [comment]
Done. Hope it's now up to par!

**Review by apitiot — COMMENTED** [review]
Getting closer.
As per my previous message, we typically use: setSeed(seed, log)
And we change the value of the attribute as such:

this._setAttribute('seed', seed, log);
this.rng = XXX

And since rng is internal, I would actually change the name to:
this._randomGenerator

**Comment by tpronk** [comment]
How close are we now? :)

**Comment by apitiot** [comment]
It's functionally correct but still different from our standard approach :-P

newSeed -> seed (as per my previous message...)
if (this.seed !== undefined) -> if (typeof seed !== 'undefined')

**Comment by tpronk** [comment]
Done. Some of the things I learned en route might make a nice little contributor guide. I wonder, this `_setAttribute` and `_addAttribute` pattern in `PsychoObject`, is that some kind of standard approach I'm unaware of?

**Comment by apitiot** [comment]
It's an approach I put together myself but it is quite possibly common.
Your fix is yet again not quite what I wrote (I wonder why you resist :-P) but it's close enough.

**Comment by tpronk** [comment]
What's the fun in me not resisting? ;). Coolio, but I'd still like to know
what you would have liked differently, so I know what to annoy you with
next time

**Comment by thewhodidthis** [comment]
Closes #373

**Pull request merged**
