### PR TITLE
Make PsychoJS test-ready again

### LINKED ISSUE #369: Add correct version number in package.json
This makes it easier for psychojs_testing to read in the version number and compile test-experiments accordingly

### LINKED ISSUE #370: Log errors handled via window.onunhandledrejection in document.data-error
This helps our testing system log those errors

### LINKED ISSUE #371: installing the repo doesn't work on GH workflows
This is due to [a bug](https://github.com/actions/setup-node/issues/214) in `package-lock.json` files generated by NPM v7

### PR DESCRIPTION
**Pull request by tpronk**
This PR contains a number of improvements needed for our automated testing (via GitHub workflows):
- Add version number `2021.2.0` to package.json. Closes #369 
- Log errors captured by `window.onunhandledrejection` into `document.data-error`. Closes #370
- Workaround for [a bug](https://github.com/actions/setup-node/issues/214) in `package-lock.json` files generated by NPM v7. Closes #371

### CODE REVIEW

**Comment by thewhodidthis** [comment]
@tpronk Sorry, where is the issue that this PR is meant to address?

**Comment by tpronk** [comment]
There is none; it's all about things I encountered as I was making my fork of PsychoJS ready for testing. Would you like me to issueify the PR?

**Comment by thewhodidthis** [comment]
Would be nice, yes

**Comment by tpronk** [comment]
If have completified issueification

**Comment by thewhodidthis** [comment]
@tpronk Thanks, OK what happens if `error.reason` itself is `undefined`? It looks like using the optional chaining operator might be handy in this context

**Comment by tpronk** [comment]
Thanks for the suggestion! I added conditional chaining throughout `window.onunhandledrejection`

**Comment by thewhodidthis** [comment]
OK much better, thanks, why are you returning `true` though?

**Comment by tpronk** [comment]
It was already there; I just didn't change it. I suspect it might be to ensure the event bubbles up, but I don't see anything like that in the API. https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onunhandledrejection

**Comment by thewhodidthis** [comment]
Alright, thanks for confirming, good enough for the time being

**Pull request merged**
