### PR TITLE
util/Clock: drop moment and the format argument from getDateStr()

### LINKED ISSUE #348: Might not need moment.js anymore
Context: [momentjs.com/docs/#/-project-status &rarr;](https://momentjs.com/docs/#/-project-status/)

### PR DESCRIPTION
**Pull request by thewhodidthis**
@apitiot Use `Intl.DateTimeFormat()` plus string manipulation to replace moment.js, but lose the format argument, closes #348 

Test: [gist.github.com/thewhodidthis/617c54026b9ca0978a918630c0a4da97 &rarr;](https://gist.github.com/thewhodidthis/617c54026b9ca0978a918630c0a4da97)

### CODE REVIEW

**Comment by thewhodidthis** [comment]
Please note that as a result of this change data files are timestamped independent of participants' time zone

**Comment by apitiot** [comment]
I would prefer we stuck with the participant's time zone. Whenever something wrong happens with an experiment or a participant, the designer will typically have access to the local participant time (as known to the participant) rather than a UTC time. I.e. the participant will tell the designer: "I ran this yesterday at 14h".
The server log times are UTC, the participant filename have local time in them, and so, equipped with both, I can easily zero in on a particular session and track down potential problems.
Does that make sense?

**Comment by thewhodidthis** [comment]
Yes it does, but that local timestamp can be part of `expInfo` in the boilerplate and that would make it available in the logs themselves. We discussed that possibility with the rest of the team yesterday with no objections raised.

**Comment by thewhodidthis** [comment]
@apitiot Should be okay now, using Canada style formatting for easier parsing

**Comment by apitiot** [comment]
It just occurred to me that the new approach does not make it possible for people to specify the date format, as was previously the case.
Do you think we could deal with that, without re-introducing a new library and without having to implement our own parser?

**Comment by thewhodidthis** [comment]
@apitiot I have added a separate `Monotonic.getDate()` static method as a convenience wrapper around `Intl.DateTimeFormat`, which should allow for extensive date formatting on demand. The output of `Monotonic.getDateStr()` remains unchanged.

**Pull request merged**
